import{a as $,S as f,i as y}from"./assets/vendor-cc3f2068.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&l(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const w="34554984-68074c5646cb7a45ce2c04cbc";async function m(o,t){const{data:i}=await $(`https://pixabay.com/api/?key=${w}&q=${o}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}`);return i}const S=document.querySelector(".gallery");function p(o){console.log(o);const t=o.map(i=>{const{id:l,largeImageURL:e,webformatURL:r,tags:s,likes:h,views:b,comments:v,downloads:L}=i;return`
        <a class="gallery__link" href="${e}">
          <div class="gallery-item" id="${l}">
            <img class="gallery-item__img" src="${r}" alt="${s}" loading="lazy" />
            <div class="info">
              <p class="info-item"><b>Likes</b>${h}</p>
              <p class="info-item"><b>Views</b>${b}</p>
              <p class="info-item"><b>Comments</b>${v}</p>
              <p class="info-item"><b>Downloads</b>${L}</p>
            </div>
          </div>
        </a>
      `}).join("");S.insertAdjacentHTML("beforeend",t)}const g=document.querySelector("#search-form"),q=document.querySelector(".gallery"),n=document.querySelector(".btn-load-more");let c="",a=1,d=new f(".gallery a");const u=40;g.addEventListener("submit",k);n.addEventListener("click",E);n.style.visibility="hidden";async function k(o){if(o.preventDefault(),a=1,c=o.currentTarget.searchQuery.value.trim(),q.innerHTML="",g.reset(),n.style.visibility="hidden",c===""){M();return}try{const t=await m(c,a,u);t.totalHits===0&&alertNoImagesFound(),p(t.hits),d.refresh(),H(t),t.totalHits>u&&(n.style.visibility="visible")}catch(t){console.log(t)}finally{}}async function E(){a+=1,d.destroy();try{const o=await m(c,a,u);p(o.hits),d=new f(".gallery a").refresh();const t=Math.ceil(o.totalHits/u);a>t&&(n.style.visibility="hidden",alertEndOfSearch())}catch(o){console.log(o)}}function H(o){y.success({title:"Wow!",message:`Hooray! We found ${o.totalHits} images.`,position:"topRight"})}function M(){y.error({title:"Error!",message:"The search string cannot be empty. Please specify your search query.",position:"topRight"})}
//# sourceMappingURL=commonHelpers.js.map
